name: CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: mymindstorm/setup-emsdk@v12
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install
        run: pnpm i
      - name: Build
        run: pnpm build
